### ISSUE TITLE
options are grayed out

### ISSUE THREAD

**Issue by nigelmerle** [soupday/cc3_blender_tools#26]
hello this is to inform that options are grayed out in latest version of blender

the options grayed are:
import morph
import accessory
export to cc3

when i try to import fbx shen clicking on import character i get many error messages

**Comment by nigelmerle** [comment]
Is it possible for you to allow us to import other fbx files rather than
cc3 files only?
I think it would be a nice feature, i enjoy the lighting and other
configurations

**Comment by soupday** [comment]
I can only set up the CC3 files properly because it exports additional data with the FBX that I can use to set up the materials and textures, and the object and material names have a specific naming and folder structure that makes it easy to find them.

With other Fbx files, there is no way to know which textures belong to which materials, or even where those textures are located. So much information is lost in the FBX format as it doesn't support PBR texture channels like metallic, roughness, subsurface, etc.

**Comment by nigelmerle** [comment]
Last time i was trying to import an fbx and miraculously it opened without
errors, i did not know what i did. But i remember that the plug-in assigned
hair shader to the material. And the character was displaying well, when i
reinstalled the plugin now it is not working. Don't know why but really
like the fact that you have the material options that you can change to
opaque...etc
In blender it is always a nightmare to find everything and your plugin is
very organized.
In the latest version why it is not impossible to select a non cc3 mesh to
export it as an accessory in character creator. This is s bit frustrating
because in character creator we have the option import any obj of fbx as an
accessory and in cc3 we can automatically make it follow cc3 character so,
this shouldn't be a problem to export non cc3 meshes made in blender.
Also i would like to ask you about your other cc3 auto setup plugin for
character creator, i have been reading your documentation and i am a bit
confused about how to install it. Could you update the readme on github.
Which folder do i need to paste and where?, In blender or character
creator?, Because i understand that both use python scripts....i tried to
paste folder in character creator but nothing happened. Can you help me on
that one.

**Comment by soupday** [comment]
"In the latest version why it is not impossible to select a non cc3 mesh to
export it as an accessory in character creator."

It's supposed to do exactly that, but I put a condition in the wrong place to disable the button. That will be fixed soon.

"Also i would like to ask you about your other cc3 auto setup plugin for
character creator, i have been reading your documentation and i am a bit
confused about how to install it..."

It's a plugin for character creator itself. It needs to be put in a folder in the program files install folder: 

C:\Program Files\Reallusion\Character Creator 3\Bin64\OpenPlugin\CC3-Blender-Tools
(or wherever you have it installed.)

Once it's installed, you use to it re-import the characters from the Plugins > Blender auto-setup menu.

It's still in the testing stage at the moment, as you can see there are still lots of little problems to clean up, so I haven't officially announced it yet, but here is a demo video of how it works: https://youtu.be/7EXW_5rK48Y

**Comment by nigelmerle** [comment]
I tried it didnt work, i got a bunch of errors, i thought the export option was greyed also , thats why i went back to version 1.02

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nigelmerle** [comment]
I will try the autosetup tomorrow because it is 3 am here

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
