### ISSUE TITLE
bpy struct: item.attr = val: sequences of dimension 0 should contain 2 items, not 0

### ISSUE THREAD

**Issue by FNRocha** [soupday/cc3_blender_tools#42]
I am experiencing this error while trying to load a cc3 character with clothing.
![error_blender_cc3](https://user-images.githubusercontent.com/21160476/145322327-cf197ce7-f48d-4167-8474-d97d041223de.PNG)

**Comment by FNRocha** [comment]
the issue seems to be related to clothes overlapping

**Comment by soupday** [comment]
That wouldn't be the "Biker Vest" by any chance?

The UV's are completely broken in that mesh and it crashes the Blender FBX importer.
There's a version of the vest worn by a couple of sample characters that does work, that you can save out as custom clothing and use:
Template/Project/DH Sample
Template/Avatar/Clothed/Outfits_Caleb

**Comment by FNRocha** [comment]
That is exactly it, thanks for the quick reply.
