### ISSUE TITLE
Hair physics Not working

### ISSUE THREAD

**Issue by Buleto** [soupday/cc3_blender_tools#7]
Wehen i Import an animated  Charakter with hair physics the mesh explode.Why?

**Comment by soupday** [comment]
Some hair meshes do this because they have malformed polygons in them, zero length edges, loose vertices, etc.
Try cleaning up the hair mesh with degenerate dissolve.
(edit mode, select the whole mesh, then menu: mesh->clean up->degenerate dissolve)

**Comment by Buleto** [comment]
It works.
Thanks.
